project_id           = "gke-project-prueba"
zone               = "europe-west1-b"
machine_type       = "n1-standard-1"
vname         = "vm-prueba-tf-miguel"
os_image        = "rocky-linux-cloud/rocky-linux-9-v20250912"
network         = "vpc-shared"
subnetwork      = "lz-network-prueba"
service_account_email = "sa-github-actions@gke-project-prueba.iam.gserviceaccount.com"