project_id           = "gke-project-prueba"
region               = "europe-west1-b"
machine_type       = "n1-standard-1"
vname         = "vm-prueba-tf-miguel"
os_image        = "debian-cloud/debian11"
network         = "vpc-shared"
subnetwork      = "lz-network-prueba"
service_account_email = "sa-github-actions@gke-project-prueba.iam.gserviceaccount.com"