[rocky_servers]
vm_ansible ansible_host=127.0.0.1 ansible_port=2200 ansible_user=ansible ansible_ssh_private_key_file=./ansible_key.pem ansible_ssh_common_args='-o ProxyCommand="gcloud compute start-iap-tunnel <INSTANCE_NAME> 22 --zone=<ZONE> --project=<PROJECT_ID> -q --listen-on-stdin"'
