name: Terraform Compute Engine Deploy VM

on:
  push:
    branches:
      - develop 

jobs:
  deploy_vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Configure Google credentials
        shell: bash
        run: |
          echo "${GOOGLE_CREDENTIALS}" > "${GITHUB_WORKSPACE}/gcp_credentials.json"
          echo "✅ Archivo de credenciales creado en ${GITHUB_WORKSPACE}:"
          ls -l "${GITHUB_WORKSPACE}/gcp_credentials.json"
          echo "Primeras líneas:"
          head -n 5 "${GITHUB_WORKSPACE}/gcp_credentials.json"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/create_vm
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_credentials.json

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: terraform/create_vm
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_credentials.json

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: terraform/create_vm
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_credentials.json
      
      - name: Terraform output to file
        run: terraform output -json > terraform_outputs.json
        working-directory: terraform/create_vm

      - name: Upload Terraform outputs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-outputs
          path: terraform/create_vm/terraform_outputs.json
