name: Terraform and Ansible Deployment

on:
  push:
    branches:
      - develop 

jobs:
  deploy_vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Configure Google credentials
        shell: bash
        run: |
          echo "${GOOGLE_CREDENTIALS}" > "${GITHUB_WORKSPACE}/gcp_credentials.json"
          echo "✅ Archivo de credenciales creado en ${GITHUB_WORKSPACE}."
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/create_vm
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_credentials.json

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: terraform/create_vm
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_credentials.json

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: terraform/create_vm
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_credentials.json
      
      - name: Terraform output to file
        run: terraform output -json > terraform_outputs.json
        working-directory: terraform/create_vm

      - name: Upload Terraform outputs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: terraform/create_vm/terraform_outputs.json

          
  ansible:
    needs: deploy_vm
    runs-on: ubuntu-latest

    steps:
      - name: Download Terraform outputs artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-outputs
          path: ./terraform_outputs

      - name: Show downloaded terraform_outputs.json
        run: cat ./terraform_outputs/terraform_outputs.json

      - name: Read Terraform outputs and set outputs
        id: read_outputs
        run: |
          instance_name=$(jq -r '.instance_name.value' ./terraform_outputs/terraform_outputs.json)
          zone=$(jq -r '.zone.value' ./terraform_outputs/terraform_outputs.json)
          project_id=$(jq -r '.project_id.value' ./terraform_outputs/terraform_outputs.json)
          private_key_content=$(jq -r '.ansible_ssh_private_key_content.value' ./terraform_outputs/terraform_outputs.json)

          echo "INSTANCE_NAME=$instance_name" >> $GITHUB_ENV
          echo "ZONE=$zone" >> $GITHUB_ENV
          echo "PROJECT_ID=$project_id" >> $GITHUB_ENV

          echo "$private_key_content" | base64 --decode > ./private_key.pem
          chmod 600 ./private_key.pem
          echo "PRIVATE_KEY_PATH=$(pwd)/private_key.pem" >> $GITHUB_ENV

          echo "::set-output name=instance_name::$instance_name"
          echo "::set-output name=zone::$zone"
          echo "::set-output name=project_id::$project_id"
          echo "::set-output name=private_key_path::$(pwd)/private_key.pem"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ steps.read_outputs.outputs.project_id }}
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_default_credentials: true

      - name: Install Ansible and dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ansible openssh-client jq netcat

      - name: Run Ansible playbook through IAP tunnel
        env:
          GCP_PROJECT_ID: ${{ steps.read_outputs.outputs.project_id }}
          INSTANCE_NAME: ${{ steps.read_outputs.outputs.instance_name }}
          ZONE: ${{ steps.read_outputs.outputs.zone }}
          USER: ansible
          PRIVATE_KEY_PATH: ${{ steps.read_outputs.outputs.private_key_path }}
        run: |
          gcloud compute ssh $INSTANCE_NAME --zone=$ZONE --project=$GCP_PROJECT_ID --tunnel-through-iap -- \
            ansible-playbook -i "localhost," ansible/inventory.ini ansible/playbooks/install_tomcat.yml \
            --user=$USER \
            --private-key=$PRIVATE_KEY_PATH \
            -e "ansible_ssh_common_args='-o StrictHostKeyChecking=no -p 22'"
