name: Deploy to GCP VM via IAP Tunnel with Ansible

on:
  workflow_run:
    workflows: ["Terraform Compute Engine Deploy VM"] 
    types:
      - completed
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_default_credentials: true

      - name: Install Ansible on GitHub runner
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ansible openssh-client

      - name: Create IAP tunnel and run Ansible
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          # Variables
          INSTANCE_NAME=vm-prueba-tf-miguel
          ZONE=europe-west1-b
          USER=ansible

          # Open IAP tunnel (local port 2200)
          nohup gcloud compute start-iap-tunnel $INSTANCE_NAME 22 \
          --zone=$ZONE \
          --local-host-port=127.0.0.1:2200 \
          --project=$GCP_PROJECT_ID > tunnel.log 2>&1 &

          # Wait a moment for tunnel to initialize
          sleep 10

          # Run Ansible against the tunneled connection
          ansible-playbook -i "127.0.0.1," ansible/playbooks/inventory.ini ansible/playbooks/install_tomcat.yml \
            --user=$USER \
            --private-key ~/.ssh/id_rsa \
            -e "ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand=\"none\" -p 2200'"
