name: Terraform GKE Deploy

on:
  push:
    branches:
      - main            # 👈 se ejecuta automáticamente al hacer push a main
  workflow_dispatch:     # 👈 también permite lanzarlo manualmente desde GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Configure Google credentials
        shell: bash
        run: |
          echo "$GOOGLE_CREDENTIALS" > $HOME/gcp_credentials.json
          echo "✅ Archivo de credenciales creado:"
          ls -l $HOME/gcp_credentials.json
        env:
          GCP_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp_credentials.json

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp_credentials.json

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp_credentials.json
