name: Terraform GKE Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Configure Google credentials
        shell: bash
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > $HOME/gcp_credentials.json
          echo "Archivo de credenciales creado en $HOME:"
          ls -l $HOME/gcp_credentials.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Plan
        run: terraform plan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp_credentials.json

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp_credentials.json
